### ISSUE TITLE
EVM to AVM: insufficient liquidity.

### ISSUE THREAD

**Issue by Wild-er** [AramidFinance/aramid-bridge-fe-vue#23]
When refreshing the page while connected with your EVM source wallet it creates an error. For some reason it does not detect sufficent liquidity. 
Only happens if you refresh the home screen after connecting your EVM wallet.
![image](https://github.com/user-attachments/assets/c9ee7854-f2e2-4731-8692-8f4ec5d50111)

**Comment by nodesupport1** [comment]
@Wild-er You’re encountering an issue with detecting sufficient liquidity when refreshing the page after connecting your EVM source wallet. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID EVM07638
Please see the link below to our dedicated support line:
[EVM source Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by scholtz** [comment]
i cant reproduce this
