### ISSUE TITLE
AVM Wallets on Voi

### ISSUE THREAD

**Issue by Wild-er** [AramidFinance/aramid-bridge-fe-vue#39]
![image](https://github.com/user-attachments/assets/2c482717-108d-4a97-850b-9e6ce6fcd67e)
Kibisis, Lute, and Biatec aren't showing.

**Comment by scholtz** [comment]
![image](https://github.com/user-attachments/assets/764fa7ff-622d-4b2f-b172-8823378ead37)
![image](https://github.com/user-attachments/assets/7c57add3-7d4b-44fc-9d48-a44644709e92)
