### ISSUE TITLE
Bridge again button leads to wrong source or destination wallet connection

### ISSUE THREAD

**Issue by Wild-er** [AramidFinance/aramid-bridge-fe-vue#6]
<img width="650" alt="image" src="https://github.com/user-attachments/assets/21ca2fc6-5873-44fd-be5e-48c2c6b03932">
<img width="681" alt="image" src="https://github.com/user-attachments/assets/7d9b428f-45ae-4bb6-98a5-335a2a8d655f">

After completing a bridge transaction successfully, post fireworks, and clicking bridge again the Source wallet is incorrect.

After swapping Origin and Destination the problem persists.

**Comment by scholtz** [comment]
i think this is fixed
